vich_uploader:
    db_driver: orm

    mappings:
        Utilisateurs:
            uri_prefix: /images/Utilisateurs
            upload_destination: '%kernel.project_dir%/public/images/Utilisateurs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true