#index:
#    path: /
#    controller: App\Controller\DefaultController::index
  # captcha_routing:
    #  resource: "@captchaBundle/Resources/config/routing.yml"
captcha_handler:
      path: /captcha-handler
      defaults: { _controller: CaptchaBundle:CaptchaHandler:index }
      methods: [GET]

simple_captcha_handler:
      path: /simple-captcha-handler
      defaults: { _controller: CaptchaBundle:SimpleCaptchaHandler:index }
      methods: [GET]