<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW7itqAJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW7itqAJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW7itqAJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW7itqAJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerW7itqAJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'W7itqAJ',
    'container.build_id' => '5a84958f',
    'container.build_time' => 1651149906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW7itqAJ');
